### ISSUE TITLE
Switch from extension points to service loaders

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#402]
The KIELER Semantics project recently wanted to make their project more independent of Eclipse infrastructure. As a part of that, they changed the way their software components are registered. What used to be done through the standard extension point mechanisms is now done via Java service loaders which are used when running in the Eclipse context as well.

I think it would be worthy to investigate this for registering meta data providers. As of now, using ELK in plain Java mode requires clients to register meta data providers themselves, which is unfortunate. Switching to a service loader mechanism would only require them to call an initialization method instead, if at all.

What I cannot judge yet are the implications for the JavaScript version of ELK. I believe that uses a different registration mechanism anyway, but @uruuru may have to correct me there.

**Tasks**

- [x] Introduce basic service loading mechanism
- [x] Update documentation
- [x] Update New Project wizard
- [ ] Add unit tests to check whether the expected layout algorithms are properly registered

**Comment by uruuru** [comment]
Every layout plugin (i.e. jar bundle) would use it's own service loader then? 

Regarding elkjs I think it'd be fine as long as a _manual_ registration is not prohibited in some way. From a first glance at how service loaders work, I'd expect that the part that is automatically invoked by the JVM (the stuff specified in `META-INF/services`) is simply dead code from the perspective of the javascript transpiler. 

I wonder why we never considered the service loader mechanism before.

**Comment by le-cds** [comment]
Actually, ELK's infrastructure would use a service loader that provides us with implementations of BLA. It's actually a slight bit more complicated in Eclipse due to the fact that Equinox uses not one, but a number of class loaders, but the KIELER Semantics project got it to work alright, so that won't be a problem.

The basic mechanism would stay the same: people could still register things manually, but usually wouldn't have to anymore since service loaders work outside of Eclipse as well.

> I wonder why we never considered the service loader mechanism before.

I guess by the time they appeared in the Java world, we simply had no reason to switch since the Eclipse mechanisms worked just fine for our use cases back then.

**Comment by le-cds** [comment]
Note to whoever will implement this: our brand new New Layout Plug-In Project Wizard will have to be changed to add the necessary service entries instead of extensions.

**Comment by le-cds** [comment]
The KIELER implementation can be found [over here](https://git.rtsys.informatik.uni-kiel.de/projects/KIELER/repos/semantics/browse/plugins/de.cau.cs.kieler.core/src/de/cau/cs/kieler/core/services/KielerServiceLoader.xtend). It will have to be adapted, but the basics are there.

**Comment by le-cds** [comment]
Everything now works with service loaders, which means that manual registration is not required anymore when using plain java mode. For the time being, the `layoutProviders` extension point is deprecated, to be removed in a future release. This is tracked by #526.

@uruuru Manual registration is still possible. All that changed is that algorithms are not registered through the extension point anymore, but through service loaders, which ultimately uses the same methods as manual registration would.

**Comment by uruuru** [comment]
There seems to be an issue with the _order_ in which the providers are loaded. I came across the following: In a plain Java environment the `CoreOptions` end up being loaded _last_. As a consequence all options registered in other layout algorithm providers via `supports` do not end up in the `knownOptions` map of the corresponding `LayoutAlgorithmData`.

I'm not sure if the bundle-based loading in `ElkServicePlugin` happens to load `CoreOptions` early enough by chance or if dependencies are resolved there. 

A pragmatic solution would be to simply make sure `CoreOptions` are loaded first. The proper solution would be to leverage some dependency graph to derive the order.

**Comment by le-cds** [comment]
@uruuru I summoned issue #601 to help us in our quest for a solution! All hail issue #601!
